[programs.localnet]
om_universe = "64iK3xKi71fxKE6nDR8NZkEjNCFrKWCg521GsBNZ66R8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/zihua/.config/solana/id.json"

[scripts]
test-all = "mocha -t 1000000 tests/"
